PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/2cd2a0af5a52e6cf3131fbefd432c77a4c917b89

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/fdf1837077104e80912a2c46ff159fdacc8b06f9) in current PX4/master (01b280f7ae1e0b222ed0ea91062392e43b8d2c85)
https://github.com/PX4/NuttX/compare/fdf1837077104e80912a2c46ff159fdacc8b06f9...2cd2a0af5a52e6cf3131fbefd432c77a4c917b89

2cd2a0af5a (HEAD, origin/master) arm hostfs: Compile only when enabled by config (#307)
7507f78a2f boards/arm/samv7:  Fix undefined reference to _ramfuncs
d5fc2458ba boards/arm/tiva/lm3s6965-ek: Add PROTECTED support
b9682171f4 arch: armv7-a: Fix stack pointer alignment at startup
d06d8fbca2 Run all .c and .h files modified by PR301 through nxstyle.
892290f76b syslog: Call syslog_rpmsg_init inside syslog_initialize like other syslog driver
553f12b4e8 syslog: Remove SYSLOG_SERIAL_CONSOLE which isn't really used
fdf673c5c7 arch/arm/src/kinetis/kinetis_serial.c:  Correct build test failure.
85caee63b4 drivers/analog:  Adds driver for the ADS7828 I2C analog to digital converter
bff26dbe3a arch: Cleanup syslog_console_init usage

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/eb8678cfebc788b6dbaa412d75551581a6201043

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/91b6ad6a0d00ac107088b18588cd54d40e3cb796) in current PX4/master (01b280f7ae1e0b222ed0ea91062392e43b8d2c85)
https://github.com/PX4/NuttX-apps/compare/91b6ad6a0d00ac107088b18588cd54d40e3cb796...eb8678cfebc788b6dbaa412d75551581a6201043

eb8678cf (HEAD -> master, origin/master) Remove CONFIG_DEV_LOWCONSOLE from source code
56961822 Change CONFIG_CXX_NEWLONG to CONFIG_ARCH_SIZET_LONG
e55e3106 testing/fstest/fstest_main.c: Eliminate a warning found during the build test.
218d8c9f examples/elf/tests/mutex/mutex.c:  Fix typo in a previous PR.
1056cce2 apps/examples/elf:  Correct mount point configuration error.
1d8b738a apps/examples/elf:  Resolve issue issue 63
e5dd0b1e mksymtab.sh: Avoid using find -executable
d81b7af4 ntpclient: Use sem protect global variable instead sched_lock/unlock
02a800c9 ntpclient: Initialize g_ntpc_daemon at the definition
782953ff ntpclient: the 2nd arg of MKLVM should be version number